# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 257bf8d9494c628f95d65f9e09b847f85aa5dbcbf86e2c7c9c94219e243abb423a18cfc314552fa3aa39797501c1a02f8e8bcd948000a775a410c94d683c55ce

test:
  secret_key_base: c944ebfd67e66e9512c493587c0a159426eedc4628da0013f35dc2d849cc1e27e358d753bb0a0b59c4e169e81616a7d355ea1a67c6c07da3e5f564a7c13029d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
